### ISSUE TITLE
Redesign Views for Improved UI/UX Consistency using TailwindCSS

### ISSUE THREAD

**Issue by gsimei** [gsimei/game-of-life-extendi#20]
## **Title**  
"Redesign Views for Improved UI/UX Consistency"

---

## **Description**  

The current views (sign-in, sign-up, password recovery, etc.) use default Rails templates, which do not match the overall design of the application. This issue aims to redesign these views to align them with the application's UI/UX standards using TailwindCSS for styling consistency.

---

### **Goals**
1. Redesign all views for user authentication to match the application's design system.
2. Redesign all views for GameState to match the application's design system.
3. Ensure the views are responsive and work well on both mobile and desktop devices.
4. Improve the user experience (UX) by providing cleaner and more intuitive forms.

---

### **Views to Redesign**
- `Sign In` (`sessions/new`)
- `Sign Up` (`registrations/new`)
- `Forgot Password` (`passwords/new`)
- `Reset Password` (`passwords/edit`)
- `Index of GameState` (`game_states`)
- `Show of GameState` (`game_states/:id`)
- `New of GameState` (`game_states/new`)

---

### **Tasks**
1. **Setup**:
   - Generate Devise views into the application for customization using:
     ```bash
     rails generate devise:views
     ```
   - Organize views into a logical directory structure (e.g., `app/views/devise/`).

2. **Redesign Forms**:
   - Use **TailwindCSS** to style all forms.
   - Include appropriate classes for responsive design (e.g., `sm:`, `md:`, `lg:` breakpoints).
   - Ensure buttons, input fields, and error messages are visually consistent.

3. **Test and Validate**:
   - Verify that all redesigned views are functional.
   - Ensure the forms display validation errors correctly.
   - Test the views on mobile and desktop screens.

---

### **Acceptance Criteria**
- [x] All views use TailwindCSS for styling.
- [x] Forms have consistent UI components (input fields, buttons, and error messages).
- [x] Views are responsive and work across devices.
- [x] Validation errors are clearly displayed.
- [x] Views align with the overall application design.

---

### **Additional Notes**
- Collaborate with the design team to ensure adherence to the application's style guide.
- Include screenshots of the redesigned views for review in the PR.

---

### **Related Issues**
- N/A

---

### **Priority**
- **Medium**

---
